import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "GAME OF TRUMP",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.jpg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
